apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasource:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
